image: anapsix/alpine-java:8_jdk
stages:
  - build
  - test

build-jar:
    stage: build
    script:
      - ./gradlew --refresh-dependencies
      - ./gradlew clean build

run-tests:
    stage: test
    script:
      - echo "test" # TODO
