modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/gigabit101/StevesFactoryManager/issues"
displayURL="http://github.com/gigabit101/StevesFactoryManager/"
authors="Vwse,gagabit101,hnOsmium0001"

[[mods]]
modId="sfm"
version="${file.jarVersion}"
displayName="Steve's Factory Manager"
description='''
Steve's Factory Manager
'''

[[dependencies.sfm]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"